name: build

on:
  push:
    paths-ignore: 
      - README.md
  pull_request:
    paths-ignore: 
      - README.md

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macOS-12
        version:
          # - version-2-0
          - devel
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ matrix.nim-version}}

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ matrix.nim-version}}-${{ hashFiles('*.nimble') }}

    - uses: alaviss/setup-nim@0.1.1
      with:
        path: 'nim'
        version: ${{ matrix.version }}

    - name: Install Packages
      run: nimble install -d -y

    - name: test
      run: nimble test
   